#!/bin/sh

# used to set variable from docker-compose env variables
 cat <<END
  window.VUE_APP_SNWBRD_BOOTSTRAP_HOST="${VUE_APP_SNWBRD_BOOTSTRAP_HOST}";
  window.VUE_APP_SNWBRD_BOOTSTRAP_PROTOCOL="${VUE_APP_SNWBRD_BOOTSTRAP_PROTOCOL}";
  window.VUE_APP_SNWBRD_BOOTSTRAP_CHAIN_ID="${VUE_APP_SNWBRD_BOOTSTRAP_CHAIN_ID}";
  window.VUE_APP_SNWBRD_BOOTSTRAP_PORT="${VUE_APP_SNWBRD_BOOTSTRAP_PORT}";
  window.VUE_APP_SNWBRD_BOOTSTRAP_NETWORK_ID="${VUE_APP_SNWBRD_BOOTSTRAP_NETWORK_ID}";
  window.VUE_APP_SNWBRD_NODE_HOST="${VUE_APP_SNWBRD_NODE_HOST}";
  window.VUE_APP_SNWBRD_NODE_PROTOCOL="${VUE_APP_SNWBRD_NODE_PROTOCOL}";
  window.VUE_APP_SNWBRD_NODE_CHAIN_ID="${VUE_APP_SNWBRD_NODE_CHAIN_ID}";
  window.VUE_APP_SNWBRD_NODE_PORT="${VUE_APP_SNWBRD_NODE_PORT}";
  window.VUE_APP_SNWBRD_NODE_NETWORK_ID="${VUE_APP_SNWBRD_NODE_NETWORK_ID}";
END